### ISSUE TITLE
Make a way of invalidating the token, or re-authing

### ISSUE THREAD

**Issue by blackrabbit17** [AtomicTessellator/atomic_cli#3]
When I first used a fresh install, I did 
```
at project get
```

and I got back an invalid token error, but the only way to recover from this error was for me to do:
```
rm -rf ~/.config/atomict
```

and then try again.  But our users wont know to do this, can we smooth this somehow that requires the least amount of knowledge on the users behalf?  Re-auth automatically, or prompt the user and tell them to do "at auth" or something like that

Let me know what you think the easiest solution for the user is.

**Comment by sha016** [comment]
auth is now an explicit command in https://github.com/AtomicTessellator/atomic_cli/pull/4
